#
# Makefile -- baue TIKZ-Bilder
#
# (c) 2017 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	lagrange.pdf lichtkegel.pdf absturz.pdf interferometer.pdf \
	galilei.pdf labor.pdf

images:	all

absturz.pdf:	absturz.tex
	pdflatex absturz.tex

lichtkegel.pdf:	lichtkegel.tex
	pdflatex lichtkegel.tex

lagrange.pdf:	lagrange.tex
	pdflatex lagrange.tex

interferometer.pdf:	interferometer.tex
	pdflatex interferometer.tex

galilei.pdf:	galilei.tex
	pdflatex galilei.tex

labor.pdf:	labor.tex
	pdflatex labor.tex
